### ISSUE TITLE
Upgrade Issues

### ISSUE THREAD

**Issue by ellisonpatterson** [jljr222/xenforo-simple-forms#1]
Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Duplicate entry 'form-sitemap_handler_class' for key 'PRIMARY' in /home/xeno/public_html/xenforo/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/xeno/public_html/xenforo/library/Zend/Db/Statement.php(317): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/xeno/public_html/xenforo/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /home/xeno/public_html/xenforo/library/Zend/Db/Adapter/Abstract.php(574): Zend_Db_Adapter_Abstract->query('INSERT INTO `xf...', Array)
#3 /home/xeno/public_html/xenforo/library/LiquidPro/SimpleForms/Install/210501.php(162): Zend_Db_Adapter_Abstract->insert('xf_content_type...', Array)
#4 /home/xeno/public_html/xenforo/library/LiquidPro/SimpleForms/Version.php(35): LiquidPro_SimpleForms_Install_210501->install(Object(Zend_Db_Adapter_Mysqli))
#5 /home/xeno/public_html/xenforo/library/XenForo/Model/AddOn.php(211): LiquidPro_SimpleForms_Version::Install(Array, Array, Object(SimpleXMLElement))
#6 /home/xeno/public_html/xenforo/library/XenForo/Model/AddOn.php(169): XenForo_Model_AddOn->installAddOnXml(Object(SimpleXMLElement), 'LiquidPro_Simpl...')
#7 /home/xeno/public_html/xenforo/library/XenForo/ControllerAdmin/AddOn.php(237): XenForo_Model_AddOn->installAddOnXmlFromFile('/tmp/phpZwtq0C', 'LiquidPro_Simpl...')
#8 /home/xeno/public_html/xenforo/library/XenForo/FrontController.php(351): XenForo_ControllerAdmin_AddOn->actionUpgrade()
#9 /home/xeno/public_html/xenforo/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#10 /home/xeno/public_html/xenforo/admin.php(13): XenForo_FrontController->run()
#11 {main}

and then:
Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Subquery returns more than 1 row in /home/fdsa/public_html/xenforo/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/fdsa/public_html/xenforo/library/Zend/Db/Statement.php(317): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/fdsa/public_html/xenforo/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /home/fdsa/public_html/xenforo/library/LiquidPro/SimpleForms/Install/210600.php(45): Zend_Db_Adapter_Abstract->query('UPDATE `lpsf_fi...')
#3 /home/fdsa/public_html/xenforo/library/LiquidPro/SimpleForms/Version.php(35): LiquidPro_SimpleForms_Install_210600->install(Object(Zend_Db_Adapter_Mysqli))
#4 /home/fdsa/public_html/xenforo/library/XenForo/Model/AddOn.php(211): LiquidPro_SimpleForms_Version::Install(Array, Array, Object(SimpleXMLElement))
#5 /home/fdsa/public_html/xenforo/library/XenForo/Model/AddOn.php(169): XenForo_Model_AddOn->installAddOnXml(Object(SimpleXMLElement), 'LiquidPro_Simpl...')
#6 /home/fdsa/public_html/xenforo/library/XenForo/ControllerAdmin/AddOn.php(237): XenForo_Model_AddOn->installAddOnXmlFromFile('/tmp/phpNitoit', 'LiquidPro_Simpl...')
#7 /home/fdsa/public_html/xenforo/library/XenForo/FrontController.php(351): XenForo_ControllerAdmin_AddOn->actionUpgrade()
#8 /home/fdsa/public_html/xenforo/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#9 /home/fdsa/public_html/xenforo/admin.php(13): XenForo_FrontController->run()
#10 {main}

**Comment by jljr222** [comment]
What version of Simple Forms were you using before the upgrade?

**Comment by CoryManson** [comment]
I'm receiving this error as well. Trying to upgrade from 2.1.8

**Comment by ellisonpatterson** [comment]
2.1.9 and I'm willing to help with the page module or whatever it is if you give a description :) I saw that the controller for it is completely empty.

**Comment by ellisonpatterson** [comment]
Alright I did your most recent commit with the files removed and it's processing.

**Comment by jljr222** [comment]
Awesome, we have the latest commit out of 2.1.9b and that should fix it. Thanks for reporting the issue!
