### ISSUE TITLE
Excesive memory request when importing

### ISSUE THREAD

**Issue by Breixomarino** [jljr222/xenforo-simple-forms#3]
It comes from here: https://xenforo.com/community/goto/post?id=1033378#post-1033378
When I import any previously created form, it requires more than 1Gb memory to import it.
`ErrorException: Fatal Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 463895 bytes) - library/XenForo/Model/Permission.php:1661
Generated By: Breixo, 13 minutes ago
Stack Trace
#0 [internal function]: XenForo_Application::handleFatalError()
#1 {main}

Request State
array(3) {
  ["url"] => string(52) "http://www.xxx.com/admin.php?forms/import"
  ["_GET"] => array(1) {
    ["forms/import"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["server_file"] => string(0) ""
    ["_xfConfirm"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
  }
}`
Should not be a server problem, I'm on a dedicated server (32Gb RAM, 2x120Gb SSD, Intel 3,40GHz...).
John L. thinks can be something related to permissions when importing a form.
If you need any extra info just let me know.
Thanks for your help!

**Comment by Xon** [comment]
Fixed in #4

**Comment by jljr222** [comment]
Nice work Xon

**Comment by Breixomarino** [comment]
Great, thanks both!
